export { default as Home } from './Home/Home.jsx'
export { default as Services } from './Services/Services.jsx'
export { default as Courses } from './Courses/Courses.jsx'
export { default as Clients } from './Clients/Clients.jsx'
export { default as Contact } from './Contact/Contact.jsx'